global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "rust_api"
    static_configs:
      - targets: ["rust_api:8080"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
