version: '3.8'

services:
  db:
    image: postgres:16
    container_name: campus_virtual_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: campus_virtual
      # A침adir esta variable para asegurar ejecuci칩n
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d campus_virtual"]
      interval: 5s
      timeout: 5s
      retries: 5
    # A침adir esta configuraci칩n para manejar mejor los scripts
    restart: unless-stopped

  rust_api:
    build: .
    container_name: rust_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/campus_virtual
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: campus_virtual
      RUST_LOG: debug
    ports:
      - "8080:8080"
    volumes:
      - ./docker-entrypoint-initdb.d:/app/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway
    container_name: prometheus_pushgateway
    ports:
      - "9091:9091"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./tests:/tests
    entrypoint: ["k6"]
    command: ["run", "--out=influxdb=http://influxdb:8086/k6", "/tests/test_script.js"]
    depends_on:
      - rust_api
      - influxdb

volumes:
  postgres_data:
    name: campus_virtual_db_data